athenaVersion=2027.0.0-SNAPSHOT
athenaGroup=ca.frc6390.athena
athenaFrcYear=2027
athenaMavenUrl=https://maven.frc6390.ca/FRC-6390/FRC-Athena
athenaJsonUrl=https://raw.githubusercontent.com/FRC-6390/FRC-Athena/refs/heads/main/vendordeps/FRC6390-Athena.json
athenaUuid=d2f7f475-5689-461d-a3d3-33a0e4b67327
junitVersion=5.10.3
wpilibVersion=2026.2.2
ctrePhoenix6Version=26.3.0
revLibVersion=2026.0.5
studicaVersion=2026.0.0
photonLibVersion=v2026.3.4
pathPlannerLibVersion=2026.1.2
choreoLibVersion=2026.0.3
