pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
        maven {
            url = uri('https://frcmaven.wpi.edu/artifactory/release')
            content {
                includeGroupByRegex('edu\\.wpi\\.first.*')
                includeGroup('org.wpilib')
            }
        }
        maven {
            url = uri('https://maven.ctr-electronics.com/release')
            content {
                includeGroupByRegex('com\\.ctre\\.phoenix6.*')
            }
        }
        maven {
            url = uri('https://maven.revrobotics.com/')
            content {
                includeGroup('com.revrobotics.frc')
            }
        }
        maven {
            url = uri('https://dev.studica.com/maven/release/2026/')
            content {
                includeGroup('com.studica.frc')
            }
        }
        maven {
            url = uri('https://maven.photonvision.org/repository/internal')
            content {
                includeGroup('org.photonvision')
            }
        }
        maven {
            url = uri('https://3015rangerrobotics.github.io/pathplannerlib/repo')
            content {
                includeGroup('com.pathplanner.lib')
            }
        }
        maven {
            url = uri('https://frcmaven.wpi.edu/artifactory/sleipnirgroup-mvn-release/')
            content {
                includeGroup('choreo')
            }
        }
    }
}

rootProject.name = 'FRC-Athena-2027'

include 'athena-api'
include 'athena-runtime'
include 'athena-hardware'
include 'athena-mechanisms'
include 'athena-superstructure'
include 'athena-drivetrain'
include 'athena-vision'
include 'athena-localization'
include 'athena-auto'
include 'athena-commands'
include 'athena-telemetry'
include 'athena-dashboard'
include 'athena-plugin'
include 'athena-simulation'
include 'athena-wpilib'
include 'athena-vendor-ctre'
include 'athena-vendor-rev'
include 'athena-vendor-studica'
include 'athena-vendor-photonvision'
include 'athena-vendor-limelight'
include 'athena-vendor-pathplanner'
include 'athena-vendor-choreo'
include 'example-project'
